CREATE TABLE CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    DOMICILIO           VARCHAR2(100)    NOT NULL,
    CORREO              VARCHAR2(40),
    FECHA_CUMPLEAÑOS    VARCHAR2(40),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
)
;

CREATE TABLE CLIENTE_TELEFONO(
    CLIENTE_TELEFONO_ID    NUMBER(10, 0)    NOT NULL,
    TELEFONO               VARCHAR2(12)     NOT NULL,
    CLIENTE_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CLIENTE_TELEFONO_PK PRIMARY KEY (CLIENTE_TELEFONO_ID)
)
;

CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    FOLIO                NUMBER(10, 0)    NOT NULL,
    FECHA_SOLICITUD      DATE             NOT NULL,
    IMPORTE_TOTAL        NUMBER(10, 0),
    IMPORTE_SERVICIO     NUMBER(10, 0),
    IMPORTE_PRODUCTOS    NUMBER(10, 0),
    CLIENTE_ID           NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ORDEN_COMPRA_PK PRIMARY KEY (ORDEN_COMPRA_ID)
)
;

CREATE TABLE SERVICIO_ORDEN_COMPRA(
    SERVICIO_ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID                 NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SERVICIO_ORDEN_COMPRA_PK PRIMARY KEY (SERVICIO_ORDEN_COMPRA_ID)
)
;

CREATE TABLE INVENTARIO_PRODUCTO(
    INVENTARIO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID           NUMBER(10, 0),
    NUM_INVENTARIO            NUMBER(10, 0)    NOT NULL,
    FECHA                     TIMESTAMP(6)     NOT NULL,
    VETERINARIA_ID            NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT INVENTARIO_PRODUCTO__PK PRIMARY KEY (INVENTARIO_PRODUCTO_ID)
)
;

CREATE TABLE CATALOGO_PRODUCTO(
    CATALOGO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    PRECIO                  NUMBER(10, 2)    NOT NULL,
    DESCRIPCION             VARCHAR2(150)    NOT NULL,
    CONSTRAINT CATALOGO_PRODUCTO_PK PRIMARY KEY (CATALOGO_PRODUCTO_ID)
)
;

CREATE TABLE PRODUCTO_CATEGORIA(
    PRODUCTO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID     NUMBER(10, 0)    NOT NULL,
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO                   NUMBER(5, 0)     NOT NULL,
    FECHA                    DATE             NOT NULL,
    CONSTRAINT PRODUCTO_CATEGORIA_PK PRIMARY KEY (PRODUCTO_CATEGORIA_ID)
)
;

CREATE TABLE CATALOGO_CATEGORIA(
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    CATEGORIA                VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATALOGO_CATEGORIA_PK PRIMARY KEY (CATALOGO_CATEGORIA_ID)
)
;

CREATE TABLE ESTATUS_INVENTATIO_HISTORICO(
    ID                        NUMBER(10, 0)    NOT NULL,
    FECHA                     DATE,
    ESTATUS_PRODUCTO_ID       NUMBER(10, 0)    NOT NULL,
    INVENTARIO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ESTATUS_INVENTATIO_HISTORICO_PK PRIMARY KEY (ID)
)
;

CREATE TABLE ESTATUS_PRODUCTO(
    ESTATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    VALOR                  VARCHAR2(12)     NOT NULL,
    FECHA_ESTATUS          DATE             NOT NULL,
    CONSTRAINT ESTATUS_PRODUCTO_PK PRIMARY KEY (ESTATUS_PRODUCTO_ID)
)
;

