--@Autor: Jorge Francisco Pereda Ceballos, Brandon Cervantes Rubí,  Alexis Isaac Alcocer Diaz
--@Fecha: 03/11/2024
--@Descripción: DDL para creación de tablas para el módulo ADMIN
------------ MODULO 1
Prompt Creando TABLAS para el modulo de RH
Prompt conectando a petcare_pdb_rh
alter session set container=petcare_pdb_rh;

-- 
-- TABLE: CATALOGO_CURSO 
--

CREATE TABLE PET_C_RH.CATALOGO_CURSO(
    CATALOGO_CURSO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION          VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATALOGO_CURSO_PK PRIMARY KEY (CATALOGO_CURSO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_CURSO_PK_IUK ON CATALOGO_CURSO(CATALOGO_CURSO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    )    
) TABLESPACE EMPLEADO_TS 
; 

-- 
-- TABLE: EMPLEADO 
--
CREATE TABLE PET_C_RH.EMPLEADO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    SUPERVISOR_ID       NUMBER(10, 0)    NOT NULL,
    ES_TUTOR            CHAR(1)          NOT NULL,
    ES_TITULAR          CHAR(1)          NOT NULL,
    EDAD                NUMBER(2, 0)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    RFC                 VARCHAR2(13)     NOT NULL,
    TELEFONO            CHAR(10),
    FOTO                BLOB             NOT NULL,
    VETERINARIA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX EMPLEADO_PK_IUK ON EMPLEADO(EMPLEADO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),    
    CONSTRAINT EMPLEADO_SUPERVISOR_ID_FK  FOREIGN KEY (SUPERVISOR_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
LOB (FOTO) STORE AS SECUREFILE (TABLESPACE EMPLEADO_LOB_TS)
;

-- 
-- TABLE: ESTILISTA 
--

CREATE TABLE PET_C_RH.ESTILISTA(
    EMPLEADO_ID    NUMBER(10, 0)     NOT NULL,
    RESENIA         VARCHAR2(4000)    NOT NULL,
    CONSTRAINT ESTILISTA_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTILISTA_PK_IUK ON ESTILISTA(EMPLEADO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),         
    CONSTRAINT EMPLEADO_ESTILISTA_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

-- 
-- TABLE: VENDEDOR 
--

CREATE TABLE PET_C_RH.VENDEDOR(
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    NUM_MIN_ORDENES    NUMBER(4, 0),
    hORARIO_ENTRADA    DATE,
    HORARIO_SALIDA     DATE             NOT NULL,
    PASEO              CHAR(1),
    CONSTRAINT VENDEDOR_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX VENDEDOR_PK_IUK ON VENDEDOR(EMPLEADO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),    
    CONSTRAINT EMPLEADO_VENDEDOR_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

-- 
-- TABLE: VETERINARIO 
--

CREATE TABLE PET_C_RH.VETERINARIO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    UNIVERSIDAD         VARCHAR2(40)     NOT NULL,
    CEDULA              VARCHAR2(20)     NOT NULL,
    FECHA_TITULACION    DATE             NOT NULL,
    CONSTRAINT VETERINARIO_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX VETERINARIO_PK_IUK ON VETERINARIO(EMPLEADO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),    
    CONSTRAINT EMPLEADO_VETERINARIO_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

-- TABLE: CURSO 
--

CREATE TABLE PET_C_RH.CURSO(
    CURSO_ID             NUMBER(10, 0)    NOT NULL,
    FECHA                DATE             NOT NULL,
    ACREDITACION         BLOB             NOT NULL,
    CATALOGO_CURSO_ID    NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CURSO_PK PRIMARY KEY (CURSO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CURSO_PK_IUK ON CURSO(CURSO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),    
    CONSTRAINT CATALOGO_CURSO_CATALOGO_CURSO_ID_FK  FOREIGN KEY (CATALOGO_CURSO_ID)
    REFERENCES CATALOGO_CURSO(CATALOGO_CURSO_ID)
        USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_CURSO_FK_IUK ON CURSO(CATALOGO_CURSO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),    
    CONSTRAINT ESTILISTA_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES ESTILISTA(EMPLEADO_ID)
        USING INDEX (
        CREATE UNIQUE INDEX ESTILISTA_FK_IUK CURSO(EMPLEADO_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    )
) TABLESPACE EMPLEADO_TS 
LOB (ACREDITACION) STORE AS SECUREFILE (TABLESPACE EMPLEADO_LOB_TS)
;


-- 
-- TABLE: VETERINARIA 
--

CREATE TABLE PET_C_RH.VETERINARIA(
    VETERINARIA_ID           NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    DIRECCION                VARCHAR2(100)    NOT NULL,
    LATITUD                  VARCHAR2(20)     NOT NULL,
    LONGITUD                 VARCHAR2(20)     NOT NULL,
    HORARIO_SEMANA_INICIO    DATE             NOT NULL,
    HORARIO_SEMANA_FIN       TIMESTAMP(6),
    HORARIO_SABADO_FIN       TIMESTAMP(6)     NOT NULL,
    HORARIO_SABADO_INICIO    CHAR(10),
    EMPLEADO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT VETERINARIA_PK PRIMARY KEY (VETERINARIA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX VETERINARIA_PK_IUK ON VETERINARIA(VETERINARIA_ID)
        TABLESPACE EMPLEADO_IDXS_TS
    ),    
    CONSTRAINT VENDEDOR_VETERINARIA_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES VENDEDOR(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

------------ MODULO 2 

--@Autor: Jorge Francisco Pereda Ceballos / Brandon Cervantes Rubí / Alexis Isaac Alcocer Diaz
--@Fecha: 03/11/2024
--@Descripción: DDL para creación de tablas para el módulo SERVICIOS

Prompt Creando TABLAS para el modulo de RH
Prompt conectando a petcare_pdb_rh
alter session set container=petcare_pdb_rh;

--------------------- TABLAS DE SERVICIO ----------------------------

-- 
-- TABLE: CATALOGO_DIAGNOSTICO 
--

CREATE TABLE PET_C_SERVICIO.CATALOGO_DIAGNOSTICO(
    CATALOGO_DIAGNOSTICO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE                      CHAR(10),
    NIVEL_GRAVEDAD             NUMBER(1, 0)     NOT NULL,
    COSTO                      NUMBER(8, 2)     NOT NULL,
    NOMBRE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION                VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATALOGO_DIAGNOSTICO_PK PRIMARY KEY (CATALOGO_DIAGNOSTICO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_DIAGNOSTICO_PK_IUK ON CATALOGO_DIAGNOSTICO(CATALOGO_DIAGNOSTICO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    )    
) TABLESPACE SERVICIO_TS
;

-- 
-- TABLE: ESTETICA 
--

CREATE TABLE PET_C_SERVICIO.ESTETICA(
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ESTETICA_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO         NUMBER(10, 0)    NOT NULL,
    FECHA          DATE             NOT NULL,
    DESCRIPCION    BLOB             NOT NULL,
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    MASCOTA_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ESTETICA_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTETICA_PK_IUK ON ESTETICA(SERVICIO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT SERVICIO_ESTETICA_SERVICIO_ID_FK  FOREIGN KEY (SERVICIO_ID),
    REFERENCES SERVICIO(SERVICIO_ID),        
    CONSTRAINT MASCOTA_ESTETICA_MASCOTA_ID_FK  FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(MASCOTA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX MASCOTA_ESTETICA_MASCOTA_FK_IUK ON ESTETICA(MASCOTA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    )
) TABLESPACE SERVICIO_TS
LOB (DESCRIPCION) STORE AS SECUREFILE (TABLESPACE SERVICIO_LOB_TS)
;

-- 
-- TABLE: GALERIA_ESTETICA 
--

CREATE TABLE PET_C_SERVICIO.GALERIA_ESTETICA(
    GALERIA_ESTETICA_ID    NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID            NUMBER(10, 0),
    EVIDENCIA              BLOB,
    CONSTRAINT GALERIA_ESTETICA_PK PRIMARY KEY (GALERIA_ESTETICA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX GALERIA_ESTETICA_PK_IUK ON GALERIA_ESTETICA(GALERIA_ESTETICA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT SERVICIO_GALERIA_ESTETICA_SERVICIO_ID_FK  FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)    
) TABLESPACE SERVICIO_TS
LOB (EVIDENCIA) STORE AS SECUREFILE (TABLESPACE SERVICIO_LOB_TS)
;


-- 
-- TABLE: GALERIA_MASCOTA 
--

CREATE TABLE PET_C_SERVICIO.GALERIA_MASCOTA(
    GALERIA_MASCOTA_ID    NUMBER(10, 0)    NOT NULL,
    FOTO                  BLOB             NOT NULL,
    MASCOTA_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT GALERIA_MASCOTA_PK PRIMARY KEY (GALERIA_MASCOTA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX GALERIA_MASCOTA_PK_IUK ON GALERIA_MASCOTA(GALERIA_MASCOTA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    )
) TABLESPACE SERVICIO_TS
LOB (FOTO) STORE AS SECUREFILE (TABLESPACE SERVICIO_LOB_TS)
;

-- 
-- TABLE: MASCOTA 
--

CREATE TABLE PET_C_SERVICIO.MASCOTA(
    MASCOTA_ID          NUMBER(10, 0)    NOT NULL,
    RAZA                VARCHAR2(20)     NOT NULL,
    PESO                VARCHAR2(2)      NOT NULL,
    RASGOS              VARCHAR2(40),
    NOMBRE              VARCHAR2(40)     NOT NULL,
    EDAD                NUMBER(2, 0)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT MASCOTA_PK PRIMARY KEY (MASCOTA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX MASCOTA_PK_IUK ON MASCOTA(MASCOTA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    )            
) TABLESPACE SERVICIO_TS
;


-- 
-- TABLE: MEDICO 
--

CREATE TABLE PET_C_SERVICIO.MEDICO(
    SERVICIO_ID                NUMBER(10, 0)    NOT NULL,
    FECHA_REVISION             DATE             NOT NULL,
    DESCRIPCION_PROBLEMA       VARCHAR2(100)    NOT NULL,
    COSTO                      NUMBER(10, 2),
    MASCOTA_ID                 NUMBER(10, 0)    NOT NULL,
    CATALOGO_DIAGNOSTICO_ID    NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID                NUMBER(10, 0)    NOT NULL,
    CONSTRAINT MEDICO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX MEDICO_PK_IUK ON MEDICO(MEDICO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT SERVICIO_MEDICO_SERVICIO_ID_FK  FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_MEDICO_SERVICIO_FK_IUK ON MEDICO(SERVICIO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),            
    CONSTRAINT CATALOGO_DIAGNOSTICO_MEDICO_CATALOGO_DIAGNOSTICO_ID_FK  FOREIGN KEY (CATALOGO_DIAGNOSTICO_ID)
    REFERENCES CATALOGO_DIAGNOSTICO(CATALOGO_DIAGNOSTICO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_DIAGNOSTICO_MEDICO_CATALOGO_DIAGNOSTICO_FK_IUK ON MEDICO(CATALOGO_DIAGNOSTICO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT MASCOTA_MEDICO_MASCOTA_ID_FK  FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(CATALOGO_PRODUCTO_ID)
        USING INDEX (
        CREATE UNIQUE INDEX MASCOTA_MEDICO_MASCOTA__PK_IUK ON MEDICO(MASCOTA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
) TABLESPACE SERVICIO_TS
;



-- 
-- TABLE: PASEO 
--

CREATE TABLE PET_C_SERVICIO.PASEO(
    SERVICIO_ID     NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO    TIMESTAMP(6)     NOT NULL,
    FECHA_FIN       TIMESTAMP(6)     NOT NULL,
    EMPLEADO_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PASEO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PASEO_PK_IUK ON PASEO(SERVICIO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT SERVICIO_PASEO_SERVICIO_ID_FK  FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
) TABLESPACE SERVICIO_TS
;



-- 
-- TABLE: PASEO_MASCOTA 
--

CREATE TABLE PET_C_SERVICIO.PASEO_MASCOTA(
    PASEO_MASCOTA_ID    NUMBER(10, 0)    NOT NULL,
    COSTO               NUMBER(10, 2),
    SERVICIO_ID         NUMBER(10, 0)    NOT NULL,
    MASCOTA_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PASEO_MASCOTA_PK PRIMARY KEY (PASEO_MASCOTA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PASEO_MASCOTA_PK_IUK ON PASEO_MASCOTA(PASEO_MASCOTA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),            
    CONSTRAINT SERVICIO_PASEO_MASCOTA_SERVICIO_ID_FK  FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_PASEO_MASCOTA_SERVICIO_FK_IUK ON PASEO_MASCOTA(SERVICIO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT MASCOTA_PASEO_MASCOTA_MASCOTA_ID_FK  FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(MASCOTA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX MASCOTA_PASEO_MASCOTA_MASCOTA_FK_IUK ON PASEO_MASCOTA(MASCOTA_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
) TABLESPACE SERVICIO_TS
;


-- 
-- TABLE: SERVICIO 
--

CREATE TABLE PET_C_SERVICIO.SERVICIO(
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ES_MEDICO      CHAR(1)          NOT NULL,
    ES_PASEO       CHAR(1)          NOT NULL,
    ES_ESTETICA    CHAR(1)          NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_PK_IUK ON SERVICIO(SERVICIO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    )        
) TABLESPACE SERVICIO_TS
;

-- 
-- TABLE: UBICACION_EMPLEADO 
--

CREATE TABLE PET_C_SERVICIO.UBICACION_EMPLEADO(
    UBICACION_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                    DATE             NOT NULL,
    HORA                     NUMBER(2, 0)     NOT NULL,
    SEGUNDO                  NUMBER(10, 0)    NOT NULL,
    MINUTO                   NUMBER(2, 0)             NOT NULL,
    LATITUD                  VARCHAR2(10)     NOT NULL,
    LONGITUD                 VARCHAR2(10)     NOT NULL,
    SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT UBICACION_EMPLEADO_PK PRIMARY KEY (UBICACION_EMPLEADO_ID),
    USING INDEX (
        CREATE UNIQUE INDEX UBICACION_EMPLEADO_PK_IUK ON UBICACION_EMPLEADO(UBICACION_EMPLEADO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
    CONSTRAINT SERVICIO_UBICACION_EMPLEADO_SERVICIO_ID_FK  FOREIGN KEY (SERVICIO_ID)
    REFERENCES PASEO(SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_UBICACION_EMPLEADO_FK_IUK ON UBICACION_EMPLEADO(SERVICIO_ID)
        TABLESPACE SERVICIO_IDXS_TS
    ),        
) TABLESPACE SERVICIO_TS
;

------------ MODULO 3

--@Autor: Jorge Francisco Pereda Ceballos, Brandon Cervantes Rubí,  Alexis Isaac Alcocer Diaz
--@Fecha: 03/11/2024
--@Descripción: DDL para creación de tablas para el módulo VENTAS

Prompt Creando TABLAS para el modulo de RH
Prompt conectando a petcare_pdb_rh
alter session set container=petcare_pdb_rh;

CREATE TABLE PET_C_VENTA.CATALOGO_CATEGORIA(
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    CATEGORIA                VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATALOGO_CATEGORIA_PK PRIMARY KEY (CATALOGO_CATEGORIA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_CATEGORIA_PK_IUK ON CATALOGO_CATEGORIA(CATALOGO_CATEGORIA_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: CATALOGO_PRODUCTO 
--

CREATE TABLE PET_C_VENTA.CATALOGO_PRODUCTO(
    CATALOGO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    PRECIO                  NUMBER(10, 2)    NOT NULL,
    DESCRIPCION             VARCHAR2(150)    NOT NULL,
    CONSTRAINT CATALOGO_PRODUCTO_PK PRIMARY KEY (CATALOGO_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_PRODUCTO_PK_IUK ON CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: PRODUCTO_CATEGORIA 
--

CREATE TABLE PET_C_VENTA.PRODUCTO_CATEGORIA(
    PRODUCTO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID     NUMBER(10, 0)    NOT NULL,
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO                   NUMBER(5, 0)     NOT NULL,
    FECHA                    DATE             NOT NULL,
    CONSTRAINT PRODUCTO_CATEGORIA_PK PRIMARY KEY (PRODUCTO_CATEGORIA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PRODUCTO_CATEGORIA_PK_IUK ON PRODUCTO_CATEGORIA(PRODUCTO_CATEGORIA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT CATALOGO_PRODUCTO_PRODUCTO_CATEGORIA_CATALOGO_PRODUCTO_ID_FK  FOREIGN KEY (CATALOGO_PRODUCTO_ID)
    REFERENCES CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID),
    CONSTRAINT CLIENTE_CLIENTE_ID_FK  FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PRODUCTO_CATEGORIA_CLIENTE_FK_IUK ON CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: CLIENTE 
--

CREATE TABLE PET_C_VENTA.CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    DOMICILIO           VARCHAR2(100)    NOT NULL,
    CORREO              VARCHAR2(40),
    FECHA_CUMPLEANIOS    VARCHAR2(40),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CLIENTE_PK_IUK ON CLIENTE(CLIENTE_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: CLIENTE_TELEFONO 
--

CREATE TABLE PET_C_VENTA.CLIENTE_TELEFONO(
    CLIENTE_TELEFONO_ID    NUMBER(10, 0)    NOT NULL,
    TELEFONO               VARCHAR2(12)     NOT NULL,
    CLIENTE_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CLIENTE_TELEFONO_PK PRIMARY KEY (CLIENTE_TELEFONO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CLIENTE__TELEFONO_PK_IUK ON CLIENTE_TELEFONO(CLIENTE_TELEFONO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT CLIENTE_CLIENTE_TELEFONO_CLIENTE_ID_FK  FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CLIENTE_TELEFONO_CLIENTE_FK_IUK ON CLIENTE_TELEFONO(CLIENTE_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: ESTATUS_PRODUCTO 
--

CREATE TABLE PET_C_VENTA.ESTATUS_PRODUCTO(
    ESTATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    VALOR                  VARCHAR2(12)     NOT NULL,
    FECHA_ESTATUS          DATE             NOT NULL,
    CONSTRAINT ESTATUS_PRODUCTO_PK PRIMARY KEY (ESTATUS_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTATUS_PRODUCTO_PK_IUK ON ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: ORDEN_COMPRA 
--

CREATE TABLE PET_C_VENTA.ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    FOLIO                NUMBER(10, 0)    NOT NULL,
    FECHA_SOLICITUD      DATE             NOT NULL,
    IMPORTE_TOTAL        NUMBER(10, 0),
    IMPORTE_SERVICIO     NUMBER(10, 0),
    IMPORTE_PRODUCTOS    NUMBER(10, 0),
    CLIENTE_ID           NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ORDEN_COMPRA_PK PRIMARY KEY (ORDEN_COMPRA_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX ORDEN_COMPRA_PK_IUK ON ORDEN_COMPRA(ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT CLIENTE_ORDEN_COMPRA_CLIENTE_ID_FK  FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ORDEN_COMPRA_CLIENTE_FK_IUK ON CLIENTE(CLIENTE_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: SERVICIO_ORDEN_COMPRA 
--

CREATE TABLE PET_C_VENTA.SERVICIO_ORDEN_COMPRA(
    SERVICIO_ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID                 NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SERVICIO_ORDEN_COMPRA_PK PRIMARY KEY (SERVICIO_ORDEN_COMPRA_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_ORDEN_COMPRA_PK_IUK ON SERVICIO_ORDEN_COMPRA(SERVICIO_ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT ORDN_COMP_SERV_ORDN_COMP_ORDN_COMP_ID_FK  FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_ORDEN_COMPRA_FK_IUK ON SERVICIO_ORDEN_COMPRA(SERVICIO_ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    )    
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: INVENTARIO_PRODUCTO 
--

CREATE TABLE PET_C_VENTA.INVENTARIO_PRODUCTO(
    INVENTARIO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID           NUMBER(10, 0),
    NUM_INVENTARIO            NUMBER(10, 0)    NOT NULL,
    FECHA                     TIMESTAMP(6)     NOT NULL,
    VETERINARIA_ID            NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT INVENTARIO_PRODUCTO_PK PRIMARY KEY (INVENTARIO_PRODUCTO_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX INVENTARIO_PRODUCTO_PK_IUK ON INVENTARIO_PRODUCTO(INVENTARIO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT INV_PROD_ORDN_COMP_ORDN_COMP_ID_FK  FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX INVENTARIO_PRODUCTO_ORDEN_COMPRA_FK_IUK ON INVENTARIO_PRODUCTO(ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT INV_PROD_CAT_PROD_ID_FK  FOREIGN KEY (CATALOGO_PRODUCTO_ID)
    REFERENCES CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX INVENTARIO_PRODUCTO_CAT_PRODUCTO_FK_IUK ON INVENTARIO_PRODUCTO(CATALOGO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: ESTATUS_INVENTARIO_HISTORICO 
--

CREATE TABLE PET_C_VENTA.ESTATUS_INVENTARIO_HISTORICO(
    ESTATUS_INVENTARIO_HISTORICO_ID   NUMBER(10, 0)    NOT NULL,
    FECHA                             DATE,
    ESTATUS_PRODUCTO_ID               NUMBER(10, 0)    NOT NULL,
    INVENTARIO_PRODUCTO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ESTATUS_INVENTARIO_HISTORICO_PK PRIMARY KEY (ESTATUS_INVENTARIO_HISTORICO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTATUS_INVENTARIO_HISTORICO_PK_IUK ON ESTATUS_INVENTARIO_HISTORICO(ESTATUS_INVENARIO_HISTORICO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT EST_INV_HIS_EST_PROD_EST_PROD_ID_FK  FOREIGN KEY (ESTATUS_PRODUCTO_ID)
    REFERENCES ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX EST_INV_HIS_EST_PROD_EST_PROD_FK_IUK ON ESTATUS_INVENTARIO_HISTORICO(ESTATUS_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT EST_INV_HIS_INV_PROD_ID_FK  FOREIGN KEY (INVENTARIO_PRODUCTO_ID)
    REFERENCES INVENTARIO_PRODUCTO(INVENTARIO_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX EST_INV_HIS_INV_PROD_FK_IUK ON ESTATUS_INVENTARIO_HISTORICO(INVENTARIO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: SERVICIO 
--

CREATE TABLE PET_C_VENTA.SERVICIO(
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ES_MEDICO      CHAR(1)          NOT NULL,
    ES_PASEO       CHAR(1)          NOT NULL,
    ES_ESTETICA    CHAR(1)          NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_PK_IUK ON SERVICIO(SERVICIO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;