--@Autor: Jorge Francisco Pereda Ceballos, Brandon Cervantes Rubí,  Alexis Isaac Alcocer Diaz
--@Fecha: 03/11/2024
--@Descripción: DDL para creación de tablas para el módulo ADMIN

Prompt Creando TABLAS para el modulo de RH
Prompt conectando a petcare_pdb_rh
connect sys/system as sysdba
alter session set container=petcare_pdb_rh;
connect pet_c_rh/rh123@PDB_RH
-- 
-- TABLE: CATALOGO_CURSO 
--

CREATE TABLE PET_C_RH.CATALOGO_CURSO(
    CATALOGO_CURSO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION          VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATALOGO_CURSO_PK PRIMARY KEY (CATALOGO_CURSO_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS
) TABLESPACE EMPLEADO_TS 
; 

-- 
-- TABLE: EMPLEADO 
--
CREATE TABLE PET_C_RH.EMPLEADO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    SUPERVISOR_ID       NUMBER(10, 0)    NOT NULL,
    ES_TUTOR            CHAR(1)          NOT NULL,
    ES_TITULAR          CHAR(1)          NOT NULL,
    EDAD                NUMBER(2, 0)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    RFC                 VARCHAR2(13)     NOT NULL,
    TELEFONO            CHAR(10),
    FOTO                BLOB             NOT NULL,
    VETERINARIA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS,    
    CONSTRAINT EMPLEADO_SUPERVISOR_ID_FK  FOREIGN KEY (SUPERVISOR_ID)
    REFERENCES PET_C_RH.EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
LOB (FOTO) STORE AS SECUREFILE (TABLESPACE EMPLEADO_LOB_TS)
;

-- 
-- TABLE: ESTILISTA 
--

CREATE TABLE PET_C_RH.ESTILISTA(
    EMPLEADO_ID    NUMBER(10, 0)     NOT NULL,
    RESENIA         VARCHAR2(4000)    NOT NULL,
    CONSTRAINT ESTILISTA_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS,         
    CONSTRAINT EMPLEADO_ESTILISTA_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES PET_C_RH.EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

-- 
-- TABLE: VENDEDOR 
--

CREATE TABLE PET_C_RH.VENDEDOR(
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    NUM_MIN_ORDENES    NUMBER(4, 0),
    hORARIO_ENTRADA    DATE,
    HORARIO_SALIDA     DATE             NOT NULL,
    PASEO              CHAR(1),
    CONSTRAINT VENDEDOR_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS,    
    CONSTRAINT EMPLEADO_VENDEDOR_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES PET_C_RH.EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

-- 
-- TABLE: VETERINARIO 
--

CREATE TABLE PET_C_RH.VETERINARIO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    UNIVERSIDAD         VARCHAR2(40)     NOT NULL,
    CEDULA              VARCHAR2(20)     NOT NULL,
    FECHA_TITULACION    DATE             NOT NULL,
    CONSTRAINT VETERINARIO_PK PRIMARY KEY (EMPLEADO_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS,    
    CONSTRAINT EMPLEADO_VETERINARIO_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES PET_C_RH.EMPLEADO(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;

-- TABLE: CURSO 
--

CREATE TABLE PET_C_RH.CURSO(
    CURSO_ID             NUMBER(10, 0)    NOT NULL,
    FECHA                DATE             NOT NULL,
    ACREDITACION         BLOB             NOT NULL,
    CATALOGO_CURSO_ID    NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CURSO_PK PRIMARY KEY (CURSO_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS,    
    CONSTRAINT CATALOGO_CURSO_CATALOGO_CURSO_ID_FK  FOREIGN KEY (CATALOGO_CURSO_ID)
    REFERENCES PET_C_RH.CATALOGO_CURSO(CATALOGO_CURSO_ID),    
    CONSTRAINT ESTILISTA_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES PET_C_RH.ESTILISTA(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
LOB (ACREDITACION) STORE AS SECUREFILE (TABLESPACE EMPLEADO_LOB_TS)
;


-- 
-- TABLE: VETERINARIA 
--

CREATE TABLE PET_C_RH.VETERINARIA(
    VETERINARIA_ID           NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    DIRECCION                VARCHAR2(100)    NOT NULL,
    LATITUD                  VARCHAR2(20)     NOT NULL,
    LONGITUD                 VARCHAR2(20)     NOT NULL,
    HORARIO_SEMANA_INICIO    DATE             NOT NULL,
    HORARIO_SEMANA_FIN       TIMESTAMP(6),
    HORARIO_SABADO_FIN       TIMESTAMP(6)     NOT NULL,
    HORARIO_SABADO_INICIO    CHAR(10),
    EMPLEADO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT VETERINARIA_PK PRIMARY KEY (VETERINARIA_ID)
    USING INDEX TABLESPACE EMPLEADO_IDXS_TS,    
    CONSTRAINT VENDEDOR_VETERINARIA_EMPLEADO_ID_FK  FOREIGN KEY (EMPLEADO_ID)
    REFERENCES PET_C_RH.VENDEDOR(EMPLEADO_ID)
) TABLESPACE EMPLEADO_TS 
;







