--@Autor: Jorge Francisco Pereda Ceballos, Brandon Cervantes Rubí,  Alexis Isaac Alcocer Diaz
--@Fecha: 03/11/2024
--@Descripción: DDL para creación de tablas para el módulo VENTAS


CREATE TABLE PET_C_VENTA.CATALOGO_CATEGORIA(
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    CATEGORIA                VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATALOGO_CATEGORIA_PK PRIMARY KEY (CATALOGO_CATEGORIA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_CATEGORIA_PK_IUK ON CATALOGO_CATEGORIA(CATALOGO_CATEGORIA_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: CATALOGO_PRODUCTO 
--

CREATE TABLE PET_C_VENTA.CATALOGO_PRODUCTO(
    CATALOGO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    PRECIO                  NUMBER(10, 2)    NOT NULL,
    DESCRIPCION             VARCHAR2(150)    NOT NULL,
    CONSTRAINT CATALOGO_PRODUCTO_PK PRIMARY KEY (CATALOGO_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CATALOGO_PRODUCTO_PK_IUK ON CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: PRODUCTO_CATEGORIA 
--

CREATE TABLE PET_C_VENTA.PRODUCTO_CATEGORIA(
    PRODUCTO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID     NUMBER(10, 0)    NOT NULL,
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO                   NUMBER(5, 0)     NOT NULL,
    FECHA                    DATE             NOT NULL,
    CONSTRAINT PRODUCTO_CATEGORIA_PK PRIMARY KEY (PRODUCTO_CATEGORIA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PRODUCTO_CATEGORIA_PK_IUK ON PRODUCTO_CATEGORIA(PRODUCTO_CATEGORIA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT CATALOGO_PRODUCTO_PRODUCTO_CATEGORIA_CATALOGO_PRODUCTO_ID_FK  FOREIGN KEY (CATALOGO_PRODUCTO_ID)
    REFERENCES CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID),
    CONSTRAINT CLIENTE_CLIENTE_ID_FK  FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX PRODUCTO_CATEGORIA_CLIENTE_FK_IUK ON CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: CLIENTE 
--

CREATE TABLE PET_C_VENTA.CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    DOMICILIO           VARCHAR2(100)    NOT NULL,
    CORREO              VARCHAR2(40),
    FECHA_CUMPLEANIOS    VARCHAR2(40),
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CLIENTE_PK_IUK ON CLIENTE(CLIENTE_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: CLIENTE_TELEFONO 
--

CREATE TABLE PET_C_VENTA.CLIENTE_TELEFONO(
    CLIENTE_TELEFONO_ID    NUMBER(10, 0)    NOT NULL,
    TELEFONO               VARCHAR2(12)     NOT NULL,
    CLIENTE_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT CLIENTE_TELEFONO_PK PRIMARY KEY (CLIENTE_TELEFONO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CLIENTE__TELEFONO_PK_IUK ON CLIENTE_TELEFONO(CLIENTE_TELEFONO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT CLIENTE_CLIENTE_TELEFONO_CLIENTE_ID_FK  FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX CLIENTE_TELEFONO_CLIENTE_FK_IUK ON CLIENTE_TELEFONO(CLIENTE_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: ESTATUS_PRODUCTO 
--

CREATE TABLE PET_C_VENTA.ESTATUS_PRODUCTO(
    ESTATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    VALOR                  VARCHAR2(12)     NOT NULL,
    FECHA_ESTATUS          DATE             NOT NULL,
    CONSTRAINT ESTATUS_PRODUCTO_PK PRIMARY KEY (ESTATUS_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTATUS_PRODUCTO_PK_IUK ON ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: ORDEN_COMPRA 
--

CREATE TABLE PET_C_VENTA.ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    FOLIO                NUMBER(10, 0)    NOT NULL,
    FECHA_SOLICITUD      DATE             NOT NULL,
    IMPORTE_TOTAL        NUMBER(10, 0),
    IMPORTE_SERVICIO     NUMBER(10, 0),
    IMPORTE_PRODUCTOS    NUMBER(10, 0),
    CLIENTE_ID           NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ORDEN_COMPRA_PK PRIMARY KEY (ORDEN_COMPRA_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX ORDEN_COMPRA_PK_IUK ON ORDEN_COMPRA(ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT CLIENTE_ORDEN_COMPRA_CLIENTE_ID_FK  FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ORDEN_COMPRA_CLIENTE_FK_IUK ON CLIENTE(CLIENTE_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: SERVICIO_ORDEN_COMPRA 
--

CREATE TABLE PET_C_VENTA.SERVICIO_ORDEN_COMPRA(
    SERVICIO_ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID                 NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SERVICIO_ORDEN_COMPRA_PK PRIMARY KEY (SERVICIO_ORDEN_COMPRA_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_ORDEN_COMPRA_PK_IUK ON SERVICIO_ORDEN_COMPRA(SERVICIO_ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT ORDN_COMP_SERV_ORDN_COMP_ORDN_COMP_ID_FK  FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_ORDEN_COMPRA_FK_IUK ON SERVICIO_ORDEN_COMPRA(SERVICIO_ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    )    
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: INVENTARIO_PRODUCTO 
--

CREATE TABLE PET_C_VENTA.INVENTARIO_PRODUCTO(
    INVENTARIO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID           NUMBER(10, 0),
    NUM_INVENTARIO            NUMBER(10, 0)    NOT NULL,
    FECHA                     TIMESTAMP(6)     NOT NULL,
    VETERINARIA_ID            NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT INVENTARIO_PRODUCTO_PK PRIMARY KEY (INVENTARIO_PRODUCTO_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX INVENTARIO_PRODUCTO_PK_IUK ON INVENTARIO_PRODUCTO(INVENTARIO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT INV_PROD_ORDN_COMP_ORDN_COMP_ID_FK  FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
    USING INDEX (
        CREATE UNIQUE INDEX INVENTARIO_PRODUCTO_ORDEN_COMPRA_FK_IUK ON INVENTARIO_PRODUCTO(ORDEN_COMPRA_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT INV_PROD_CAT_PROD_ID_FK  FOREIGN KEY (CATALOGO_PRODUCTO_ID)
    REFERENCES CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX INVENTARIO_PRODUCTO_CAT_PRODUCTO_FK_IUK ON INVENTARIO_PRODUCTO(CATALOGO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: ESTATUS_INVENTARIO_HISTORICO 
--

CREATE TABLE PET_C_VENTA.ESTATUS_INVENTARIO_HISTORICO(
    ESTATUS_INVENTARIO_HISTORICO_ID   NUMBER(10, 0)    NOT NULL,
    FECHA                             DATE,
    ESTATUS_PRODUCTO_ID               NUMBER(10, 0)    NOT NULL,
    INVENTARIO_PRODUCTO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT ESTATUS_INVENTARIO_HISTORICO_PK PRIMARY KEY (ESTATUS_INVENTARIO_HISTORICO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX ESTATUS_INVENTARIO_HISTORICO_PK_IUK ON ESTATUS_INVENTARIO_HISTORICO(ESTATUS_INVENARIO_HISTORICO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT EST_INV_HIS_EST_PROD_EST_PROD_ID_FK  FOREIGN KEY (ESTATUS_PRODUCTO_ID)
    REFERENCES ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID) 
    USING INDEX (
        CREATE UNIQUE INDEX EST_INV_HIS_EST_PROD_EST_PROD_FK_IUK ON ESTATUS_INVENTARIO_HISTORICO(ESTATUS_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    ),
    CONSTRAINT EST_INV_HIS_INV_PROD_ID_FK  FOREIGN KEY (INVENTARIO_PRODUCTO_ID)
    REFERENCES INVENTARIO_PRODUCTO(INVENTARIO_PRODUCTO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX EST_INV_HIS_INV_PROD_FK_IUK ON ESTATUS_INVENTARIO_HISTORICO(INVENTARIO_PRODUCTO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;

-- 
-- TABLE: SERVICIO 
--

CREATE TABLE PET_C_VENTA.SERVICIO(
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ES_MEDICO      CHAR(1)          NOT NULL,
    ES_PASEO       CHAR(1)          NOT NULL,
    ES_ESTETICA    CHAR(1)          NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
    USING INDEX (
        CREATE UNIQUE INDEX SERVICIO_PK_IUK ON SERVICIO(SERVICIO_ID)
        TABLESPACE VENTA_IDXS_TS
    )
) TABLESPACE VENTA_TS 
;


