--@Autor: Jorge Francisco Pereda Ceballos / Brandon Cervantes Rubí / Alexis Isaac Alcocer Diaz
--@Fecha: 03/11/2024
--@Descripción: Creación de indices para el módulo de SERVICIO

Prompt Conectando a petcare_pdb_servicio
connect sys/system as sysdba
alter session set container=petcare_pdb_servicio;
connect pet_c_servicio/servicio123@PDB_SERVICIO

-- Índices para llaves foráneas
--

-- Índice para GALERIA_ESTETICA.SERVICIO_ID
CREATE INDEX PET_C_SERVICIO.GALERIA_ESTETICA_SERVICIO_ID_IDX
    ON PET_C_SERVICIO.GALERIA_ESTETICA (SERVICIO_ID)
    TABLESPACE SERVICIO_IDXS_TS;

-- Índice para GALERIA_MASCOTA.MASCOTA_ID
CREATE INDEX PET_C_SERVICIO.GALERIA_MASCOTA_MASCOTA_ID_IDX
    ON PET_C_SERVICIO.GALERIA_MASCOTA (MASCOTA_ID)
    TABLESPACE SERVICIO_IDXS_TS;


-- Índice para ESTETICA.MASCOTA_ID
CREATE INDEX PET_C_SERVICIO.ESTETICA_MASCOTA_ID_IDX
    ON PET_C_SERVICIO.ESTETICA (MASCOTA_ID)
    TABLESPACE SERVICIO_IDXS_TS;


-- Índice para MEDICO.CATALOGO_DIAGNOSTICO_ID
CREATE INDEX PET_C_SERVICIO.MEDICO_CATALOGO_DIAGNOSTICO_ID_IDX
    ON PET_C_SERVICIO.MEDICO (CATALOGO_DIAGNOSTICO_ID)
    TABLESPACE SERVICIO_IDXS_TS;

-- Índice para MEDICO.MASCOTA_ID
CREATE INDEX PET_C_SERVICIO.MEDICO_MASCOTA_ID_IDX
    ON PET_C_SERVICIO.MEDICO (MASCOTA_ID)
    TABLESPACE SERVICIO_IDXS_TS;



-- Índice para PASEO_MASCOTA.SERVICIO_ID
CREATE INDEX PET_C_SERVICIO.PASEO_MASCOTA_SERVICIO_ID_IDX
    ON PET_C_SERVICIO.PASEO_MASCOTA (SERVICIO_ID)
    TABLESPACE SERVICIO_IDXS_TS;

-- Índice para PASEO_MASCOTA.MASCOTA_ID
CREATE INDEX PET_C_SERVICIO.PASEO_MASCOTA_MASCOTA_ID_IDX
    ON PET_C_SERVICIO.PASEO_MASCOTA (MASCOTA_ID)
    TABLESPACE SERVICIO_IDXS_TS;    

-- Índice para UBICACION_EMPLEADO.SERVICIO_ID
CREATE INDEX PET_C_SERVICIO.UBICACION_EMPLEADO_SERVICIO_ID_IDX
    ON PET_C_SERVICIO.UBICACION_EMPLEADO (SERVICIO_ID)
    TABLESPACE SERVICIO_IDXS_TS;


-- Índice compuesto:  
-- Este índice busca por mascota y fecha en la tabla de servicios médicos.
CREATE INDEX PET_C_SERVICIO.MEDICO_MASCOTA_FECHA_IDX
    ON PET_C_SERVICIO.MEDICO (MASCOTA_ID, FECHA_REVISION)
    TABLESPACE SERVICIO_IDXS_TS;


-- Índice basado en funciones:
-- Este índice se basa en la función TRUNC para buscar servicios de estética por día.
CREATE INDEX PET_C_SERVICIO.ESTETICA_FECHA_TRUNC_IDX 
    ON PET_C_SERVICIO.ESTETICA (TRUNC(FECHA))
    TABLESPACE SERVICIO_IDXS_TS;


-- Índice para una consulta frecuente:
-- Este índice busca ubicaciones de empleados en un rango de fechas y horas específicas. 
CREATE INDEX PET_C_SERVICIO.UBICACION_EMPLEADO_FECHA_HORA_IDX
    ON PET_C_SERVICIO.UBICACION_EMPLEADO (FECHA, HORA, MINUTO)
    TABLESPACE SERVICIO_IDXS_TS;


-- Índice para buscar mascotas por nombre
CREATE INDEX PET_C_SERVICIO.MASCOTA_NOMBRE_IDX
    ON PET_C_SERVICIO.MASCOTA (NOMBRE)
    TABLESPACE SERVICIO_IDXS_TS;

-- Índice para buscar servicios de paseo por rango de fechas
CREATE INDEX PET_C_SERVICIO.PASEO_RANGO_FECHAS_IDX
    ON PET_C_SERVICIO.PASEO (FECHA_INICIO, FECHA_FIN)
    TABLESPACE SERVICIO_IDXS_TS;