insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (131, 'Shanghai Lida Polytechnic Institute', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (132, 'Aichi University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (133, 'Troy University, Montgomery', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (134, 'Shaheed Chamran University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (135, 'Lutheran Bible Institute of Seattle', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (136, 'Rhode Island College', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (137, 'Universidad de San Carlos de Guatemala', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (138, 'Grace University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (139, 'Trident University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (140, 'Islamic Azad University, Shahr-e-rey Branch', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (141, 'West Virginia University Institute of Technology', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (142, 'California State University, Channel Islands', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (143, 'Instituto Universitario de Estudios Navales y Marítimos', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (144, 'Bindura University of Science Education', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (145, 'Katholische Hochschule für Soziale Arbeit Saarbrücken', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (146, 'Universitas Muhammadiyah Jember', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (147, 'Ural State Conservatory', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (148, 'Virginia Wesleyan College', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (149, 'Nara Women''s University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (150, 'Kun Shan University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (151, 'National University of Music', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (152, 'Williams Baptist College', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (153, 'Southwest State University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (154, 'Arizona State University, Polytechnic Campus', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (155, 'The College of St. Scholastica', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (156, 'Universidade Católica de Moçambique', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (157, 'Lithunian Veterinary Academy', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (158, 'Mindanao State University', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (159, 'North Greenville College', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (160, 'Takhatmal Shrivallabh Homoeopathic Medical College', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (161, 'Universidad El Bosque', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (162, 'Shandong University of Science and Technology', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (163, 'Silliman University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (164, 'Universidad Central Dominicana de Estudio Profesionales', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (165, 'Kyoto Pharmaceutical University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (166, 'Shendi University', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (167, 'Massachusetts College of Liberal Arts', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (168, 'Planwel University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (169, 'Atlantic University', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (170, 'Godfrey Okoye University ', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (171, 'Babson College', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (172, 'Samuel Merritt College', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (173, 'Jones College', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (174, 'Ho Chi Minh City University of Foreign Languages and Information Technology', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (175, 'Western Kentucky University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (176, 'Christian Heritage College', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (177, 'Madonna University', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (178, 'Université Gamal Abdel Nasser de Conakry', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (179, 'Chung Shan Medical and Dental College', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (180, 'Manhattan College', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (181, 'Bauder College', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (182, 'Darul Huda Islamic University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (183, 'Universidad de las Américas (ULAM)', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (184, 'Hagerstown Community College', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (185, 'Universidade Lusiada', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (186, 'Islamic Azad University, Central Tehran Branch', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (187, 'Punjab University College of Information Tecnology', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (188, 'Punjab Agricultural University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (189, 'Universidad La Republica', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (190, 'Emory University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (191, 'Ulyanovsk State Technical University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (192, 'Pacific Adventist University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (193, 'Universidade Federal de Juiz de Fora', 1, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (194, 'Universidad de Guayaquil', 1, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (195, 'Jawaharlal Nehru Technological University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (196, 'Dar Al-Uloom Colleges', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (197, 'Dr. Ram Manohar Lohia Avadh University', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (198, 'Dicle (Tirgris) University', 0, 0);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (199, 'Concordia College, Ann Arbor', 0, 1);
insert into VETERINARIO (EMPLEADO_ID, UNIVERSIDAD, CEDULA, FECHA_TITULACION) values (200, 'Western Maryland College', 1, 0);
