--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      HP Inc.
-- Project :      PetCare-2.DM1
-- Author :       mrkyloren_117@gmail.com
--
-- Date Created : Tuesday, May 14, 2024 21:42:01
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CATALOGO_CATEGORIA 
--

CREATE TABLE CATALOGO_CATEGORIA(
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    CATEGORIA                VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK7_2_1_1 PRIMARY KEY (CATALOGO_CATEGORIA_ID)
)
;



-- 
-- TABLE: CATALOGO_CURSO 
--

CREATE TABLE CATALOGO_CURSO(
    CATALOGO_CURSO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    DESCRIPCION          VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK7_2_1_1_1 PRIMARY KEY (CATALOGO_CURSO_ID)
)
;



-- 
-- TABLE: CATALOGO_DIAGNOSTICO 
--

CREATE TABLE CATALOGO_DIAGNOSTICO(
    CATALOGO_DIAGNOSTICO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE                      CHAR(10),
    NIVEL_GRAVEDAD             NUMBER(1, 0)     NOT NULL,
    COSTO                      NUMBER(8, 2)     NOT NULL,
    NOMBRE                     VARCHAR2(40)     NOT NULL,
    DESCRIPCION                VARCHAR2(100)    NOT NULL,
    CONSTRAINT PK26 PRIMARY KEY (CATALOGO_DIAGNOSTICO_ID)
)
;



-- 
-- TABLE: CATALOGO_PRODUCTO 
--

CREATE TABLE CATALOGO_PRODUCTO(
    CATALOGO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE                  VARCHAR2(50)     NOT NULL,
    PRECIO                  NUMBER(10, 2)    NOT NULL,
    DESCRIPCION             VARCHAR2(150)    NOT NULL,
    CONSTRAINT PK37 PRIMARY KEY (CATALOGO_PRODUCTO_ID)
)
;



-- 
-- TABLE: CLIENTE 
--

CREATE TABLE CLIENTE(
    CLIENTE_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    DOMICILIO           VARCHAR2(100)    NOT NULL,
    CORREO              VARCHAR2(40),
    FECHA_CUMPLEAÑOS    VARCHAR2(40),
    CONSTRAINT PK1_1_1 PRIMARY KEY (CLIENTE_ID)
)
;



-- 
-- TABLE: CLIENTE_TELEFONO 
--

CREATE TABLE CLIENTE_TELEFONO(
    CLIENTE_TELEFONO_ID    NUMBER(10, 0)    NOT NULL,
    TELEFONO               VARCHAR2(12)     NOT NULL,
    CLIENTE_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK1_1_1_2 PRIMARY KEY (CLIENTE_TELEFONO_ID)
)
;



-- 
-- TABLE: CURSO 
--

CREATE TABLE CURSO(
    CURSO_ID             NUMBER(10, 0)    NOT NULL,
    FECHA                DATE             NOT NULL,
    ACREDITACION         BLOB             NOT NULL,
    CATALOGO_CURSO_ID    NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7_2_1_1_1_1 PRIMARY KEY (CURSO_ID)
)
;



-- 
-- TABLE: EMPLEADO 
--

CREATE TABLE EMPLEADO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    SUPERVISOR_ID       NUMBER(10, 0),
    ES_TUTOR            CHAR(1)          NOT NULL,
    ES_TITULAR          CHAR(1)          NOT NULL,
    EDAD                NUMBER(2, 0)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    CURP                VARCHAR2(18)     NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    RFC                 VARCHAR2(13)     NOT NULL,
    TELEFONO            CHAR(10),
    FOTO                BLOB             NOT NULL,
    VETERINARIA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: ESTATUS_INVENTATIO_HISTORICO 
--

CREATE TABLE ESTATUS_INVENTATIO_HISTORICO(
    ID                        NUMBER(10, 0)    NOT NULL,
    FECHA                     DATE,
    ESTATUS_PRODUCTO_ID       NUMBER(10, 0)    NOT NULL,
    INVENTARIO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK36 PRIMARY KEY (ID)
)
;



-- 
-- TABLE: ESTATUS_PRODUCTO 
--

CREATE TABLE ESTATUS_PRODUCTO(
    ESTATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    VALOR                  VARCHAR2(12)     NOT NULL,
    FECHA_ESTATUS          DATE             NOT NULL,
    CONSTRAINT PK7_2 PRIMARY KEY (ESTATUS_PRODUCTO_ID)
)
;



-- 
-- TABLE: ESTETICA 
--

CREATE TABLE ESTETICA(
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ESTETICA_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO         NUMBER(10, 0)    NOT NULL,
    FECHA          DATE             NOT NULL,
    DESCRIPCION    BLOB             NOT NULL,
    EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    MASCOTA_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK25 PRIMARY KEY (SERVICIO_ID)
)
;



-- 
-- TABLE: ESTILISTA 
--

CREATE TABLE ESTILISTA(
    EMPLEADO_ID    NUMBER(10, 0)     NOT NULL,
    RESEÑA         VARCHAR2(4000)    NOT NULL,
    CONSTRAINT PK1_1_1_1_1 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: GALERIA_ESTETICA 
--

CREATE TABLE GALERIA_ESTETICA(
    GALERIA_ESTETICA_ID    NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID            NUMBER(10, 0),
    EVIDENCIA              BLOB,
    CONSTRAINT PK34 PRIMARY KEY (GALERIA_ESTETICA_ID)
)
;



-- 
-- TABLE: GALERIA_MASCOTA 
--

CREATE TABLE GALERIA_MASCOTA(
    GALERIA_MASCOTA_ID    NUMBER(10, 0)    NOT NULL,
    FOTO                  BLOB             NOT NULL,
    MASCOTA_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK1_1_1_2_1 PRIMARY KEY (GALERIA_MASCOTA_ID)
)
;



-- 
-- TABLE: INVENTARIO_PRODUCTO 
--

CREATE TABLE INVENTARIO_PRODUCTO(
    INVENTARIO_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID           NUMBER(10, 0),
    NUM_INVENTARIO            NUMBER(10, 0)    NOT NULL,
    FECHA                     TIMESTAMP(6)     NOT NULL,
    VETERINARIA_ID            NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7_2_2 PRIMARY KEY (INVENTARIO_PRODUCTO_ID)
)
;



-- 
-- TABLE: MASCOTA 
--

CREATE TABLE MASCOTA(
    MASCOTA_ID          NUMBER(10, 0)    NOT NULL,
    RAZA                VARCHAR2(20)     NOT NULL,
    PESO                VARCHAR2(2)      NOT NULL,
    RASGOS              VARCHAR2(40),
    NOMBRE              VARCHAR2(40)     NOT NULL,
    EDAD                NUMBER(2, 0)     NOT NULL,
    FECHA_NACIMIENTO    DATE             NOT NULL,
    CONSTRAINT PK28 PRIMARY KEY (MASCOTA_ID)
)
;



-- 
-- TABLE: MEDICO 
--

CREATE TABLE MEDICO(
    SERVICIO_ID                NUMBER(10, 0)    NOT NULL,
    FECHA_REVISION             DATE             NOT NULL,
    DESCRIPCION_PROBLEMA       VARCHAR2(100)    NOT NULL,
    COSTO                      NUMBER(10, 2),
    MASCOTA_ID                 NUMBER(10, 0)    NOT NULL,
    CATALOGO_DIAGNOSTICO_ID    NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID                NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK23 PRIMARY KEY (SERVICIO_ID)
)
;



-- 
-- TABLE: ORDEN_COMPRA 
--

CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    FOLIO                NUMBER(10, 0)    NOT NULL,
    FECHA_SOLICITUD      DATE             NOT NULL,
    IMPORTE_TOTAL        NUMBER(10, 0),
    IMPORTE_SERVICIO     NUMBER(10, 0),
    IMPORTE_PRODUCTOS    NUMBER(10, 0),
    CLIENTE_ID           NUMBER(10, 0)    NOT NULL,
    EMPLEADO_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK1_3_1 PRIMARY KEY (ORDEN_COMPRA_ID)
)
;



-- 
-- TABLE: PASEO 
--

CREATE TABLE PASEO(
    SERVICIO_ID     NUMBER(10, 0)    NOT NULL,
    FECHA_INICIO    TIMESTAMP(6)     NOT NULL,
    FECHA_FIN       TIMESTAMP(6)     NOT NULL,
    EMPLEADO_ID     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK24 PRIMARY KEY (SERVICIO_ID)
)
;



-- 
-- TABLE: PASEO_MASCOTA 
--

CREATE TABLE PASEO_MASCOTA(
    PASEO_MASCOTA_ID    NUMBER(10, 0)    NOT NULL,
    COSTO               NUMBER(10, 2),
    SERVICIO_ID         NUMBER(10, 0)    NOT NULL,
    MASCOTA_ID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK33 PRIMARY KEY (PASEO_MASCOTA_ID)
)
;



-- 
-- TABLE: PRODUCTO_CATEGORIA 
--

CREATE TABLE PRODUCTO_CATEGORIA(
    PRODUCTO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    CATALOGO_PRODUCTO_ID     NUMBER(10, 0)    NOT NULL,
    CATALOGO_CATEGORIA_ID    NUMBER(10, 0)    NOT NULL,
    PRECIO                   NUMBER(5, 0)     NOT NULL,
    FECHA                    DATE             NOT NULL,
    CONSTRAINT PK7_2_1 PRIMARY KEY (PRODUCTO_CATEGORIA_ID)
)
;



-- 
-- TABLE: SERVICIO 
--

CREATE TABLE SERVICIO(
    SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    ES_MEDICO      CHAR(1)          NOT NULL,
    ES_PASEO       CHAR(1)          NOT NULL,
    ES_ESTETICA    CHAR(1)          NOT NULL,
    CONSTRAINT PK22 PRIMARY KEY (SERVICIO_ID)
)
;



-- 
-- TABLE: SERVICIO_ORDEN_COMPRA 
--

CREATE TABLE SERVICIO_ORDEN_COMPRA(
    SERVICIO_ORDEN_COMPRA_ID    NUMBER(10, 0)    NOT NULL,
    SERVICIO_ID                 NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK38 PRIMARY KEY (SERVICIO_ORDEN_COMPRA_ID)
)
;



-- 
-- TABLE: UBICACION_EMPLEADO 
--

CREATE TABLE UBICACION_EMPLEADO(
    UBICACION_EMPLEADO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA                    DATE             NOT NULL,
    HORA                     NUMBER(2, 0)     NOT NULL,
    SEGUNDO                  NUMBER(10, 0)    NOT NULL,
    MINUTO                   BLOB             NOT NULL,
    LATITUD                  VARCHAR2(10)     NOT NULL,
    LONGITUD                 VARCHAR2(10)     NOT NULL,
    SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK27 PRIMARY KEY (UBICACION_EMPLEADO_ID)
)
;



-- 
-- TABLE: VENDEDOR 
--

CREATE TABLE VENDEDOR(
    EMPLEADO_ID        NUMBER(10, 0)    NOT NULL,
    NUM_MIN_ORDENES    NUMBER(4, 0),
    hORARIO_ENTRADA    DATE,
    HORARIO_SALIDA     DATE             NOT NULL,
    PASEO              CHAR(1),
    CONSTRAINT PK1_2 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: VETERINARIA 
--

CREATE TABLE VETERINARIA(
    VETERINARIA_ID           NUMBER(10, 0)    NOT NULL,
    NOMBRE                   VARCHAR2(40)     NOT NULL,
    DIRECCION                VARCHAR2(100)    NOT NULL,
    LATITUD                  VARCHAR2(20)     NOT NULL,
    LONGITUD                 VARCHAR2(20)     NOT NULL,
    HORARIO_SEMANA_INICIO    DATE             NOT NULL,
    HORARIO_SEMANA_FIN       TIMESTAMP(6),
    HORARIO_SABADO_FIN       TIMESTAMP(6)     NOT NULL,
    HORARIO_SABADO_INICIO    CHAR(10),
    EMPLEADO_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK7_3_1 PRIMARY KEY (VETERINARIA_ID)
)
;



-- 
-- TABLE: VETERINARIO 
--

CREATE TABLE VETERINARIO(
    EMPLEADO_ID         NUMBER(10, 0)    NOT NULL,
    UNIVERSIDAD         VARCHAR2(40)     NOT NULL,
    CEDULA              VARCHAR2(20)     NOT NULL,
    FECHA_TITULACION    DATE             NOT NULL,
    CONSTRAINT PK1_1_1_1 PRIMARY KEY (EMPLEADO_ID)
)
;



-- 
-- TABLE: CLIENTE_TELEFONO 
--

ALTER TABLE CLIENTE_TELEFONO ADD CONSTRAINT RefCLIENTE1 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
;


-- 
-- TABLE: CURSO 
--

ALTER TABLE CURSO ADD CONSTRAINT RefCATALOGO_CURSO12 
    FOREIGN KEY (CATALOGO_CURSO_ID)
    REFERENCES CATALOGO_CURSO(CATALOGO_CURSO_ID)
;

ALTER TABLE CURSO ADD CONSTRAINT RefESTILISTA13 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES ESTILISTA(EMPLEADO_ID)
;


-- 
-- TABLE: EMPLEADO 
--

ALTER TABLE EMPLEADO ADD CONSTRAINT RefEMPLEADO21 
    FOREIGN KEY (SUPERVISOR_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
;

ALTER TABLE EMPLEADO ADD CONSTRAINT RefVETERINARIA33 
    FOREIGN KEY (VETERINARIA_ID)
    REFERENCES VETERINARIA(VETERINARIA_ID)
;


-- 
-- TABLE: ESTATUS_INVENTATIO_HISTORICO 
--

ALTER TABLE ESTATUS_INVENTATIO_HISTORICO ADD CONSTRAINT RefESTATUS_PRODUCTO26 
    FOREIGN KEY (ESTATUS_PRODUCTO_ID)
    REFERENCES ESTATUS_PRODUCTO(ESTATUS_PRODUCTO_ID)
;

ALTER TABLE ESTATUS_INVENTATIO_HISTORICO ADD CONSTRAINT RefINVENTARIO_PRODUCTO27 
    FOREIGN KEY (INVENTARIO_PRODUCTO_ID)
    REFERENCES INVENTARIO_PRODUCTO(INVENTARIO_PRODUCTO_ID)
;


-- 
-- TABLE: ESTETICA 
--

ALTER TABLE ESTETICA ADD CONSTRAINT RefSERVICIO3 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;

ALTER TABLE ESTETICA ADD CONSTRAINT RefESTILISTA9 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES ESTILISTA(EMPLEADO_ID)
;

ALTER TABLE ESTETICA ADD CONSTRAINT RefMASCOTA15 
    FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(MASCOTA_ID)
;


-- 
-- TABLE: ESTILISTA 
--

ALTER TABLE ESTILISTA ADD CONSTRAINT RefEMPLEADO31 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: GALERIA_ESTETICA 
--

ALTER TABLE GALERIA_ESTETICA ADD CONSTRAINT RefESTETICA18 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES ESTETICA(SERVICIO_ID)
;


-- 
-- TABLE: GALERIA_MASCOTA 
--

ALTER TABLE GALERIA_MASCOTA ADD CONSTRAINT RefMASCOTA4 
    FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(MASCOTA_ID)
;


-- 
-- TABLE: INVENTARIO_PRODUCTO 
--

ALTER TABLE INVENTARIO_PRODUCTO ADD CONSTRAINT RefVETERINARIA19 
    FOREIGN KEY (VETERINARIA_ID)
    REFERENCES VETERINARIA(VETERINARIA_ID)
;

ALTER TABLE INVENTARIO_PRODUCTO ADD CONSTRAINT RefORDEN_COMPRA22 
    FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
;

ALTER TABLE INVENTARIO_PRODUCTO ADD CONSTRAINT RefCATALOGO_PRODUCTO32 
    FOREIGN KEY (CATALOGO_PRODUCTO_ID)
    REFERENCES CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
;


-- 
-- TABLE: MEDICO 
--

ALTER TABLE MEDICO ADD CONSTRAINT RefMASCOTA6 
    FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(MASCOTA_ID)
;

ALTER TABLE MEDICO ADD CONSTRAINT RefCATALOGO_DIAGNOSTICO7 
    FOREIGN KEY (CATALOGO_DIAGNOSTICO_ID)
    REFERENCES CATALOGO_DIAGNOSTICO(CATALOGO_DIAGNOSTICO_ID)
;

ALTER TABLE MEDICO ADD CONSTRAINT RefSERVICIO8 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;

ALTER TABLE MEDICO ADD CONSTRAINT RefVETERINARIO11 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES VETERINARIO(EMPLEADO_ID)
;


-- 
-- TABLE: ORDEN_COMPRA 
--

ALTER TABLE ORDEN_COMPRA ADD CONSTRAINT RefCLIENTE14 
    FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE(CLIENTE_ID)
;

ALTER TABLE ORDEN_COMPRA ADD CONSTRAINT RefVENDEDOR30 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES VENDEDOR(EMPLEADO_ID)
;


-- 
-- TABLE: PASEO 
--

ALTER TABLE PASEO ADD CONSTRAINT RefSERVICIO2 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;

ALTER TABLE PASEO ADD CONSTRAINT RefVENDEDOR10 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES VENDEDOR(EMPLEADO_ID)
;


-- 
-- TABLE: PASEO_MASCOTA 
--

ALTER TABLE PASEO_MASCOTA ADD CONSTRAINT RefPASEO16 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES PASEO(SERVICIO_ID)
;

ALTER TABLE PASEO_MASCOTA ADD CONSTRAINT RefMASCOTA17 
    FOREIGN KEY (MASCOTA_ID)
    REFERENCES MASCOTA(MASCOTA_ID)
;


-- 
-- TABLE: PRODUCTO_CATEGORIA 
--

ALTER TABLE PRODUCTO_CATEGORIA ADD CONSTRAINT RefCATALOGO_PRODUCTO28 
    FOREIGN KEY (CATALOGO_PRODUCTO_ID)
    REFERENCES CATALOGO_PRODUCTO(CATALOGO_PRODUCTO_ID)
;

ALTER TABLE PRODUCTO_CATEGORIA ADD CONSTRAINT RefCATALOGO_CATEGORIA34 
    FOREIGN KEY (CATALOGO_CATEGORIA_ID)
    REFERENCES CATALOGO_CATEGORIA(CATALOGO_CATEGORIA_ID)
;


-- 
-- TABLE: SERVICIO_ORDEN_COMPRA 
--

ALTER TABLE SERVICIO_ORDEN_COMPRA ADD CONSTRAINT RefSERVICIO24 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES SERVICIO(SERVICIO_ID)
;

ALTER TABLE SERVICIO_ORDEN_COMPRA ADD CONSTRAINT RefORDEN_COMPRA25 
    FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID)
;


-- 
-- TABLE: UBICACION_EMPLEADO 
--

ALTER TABLE UBICACION_EMPLEADO ADD CONSTRAINT RefPASEO5 
    FOREIGN KEY (SERVICIO_ID)
    REFERENCES PASEO(SERVICIO_ID)
;


-- 
-- TABLE: VENDEDOR 
--

ALTER TABLE VENDEDOR ADD CONSTRAINT RefEMPLEADO23 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
;


-- 
-- TABLE: VETERINARIA 
--

ALTER TABLE VETERINARIA ADD CONSTRAINT RefVENDEDOR29 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES VENDEDOR(EMPLEADO_ID)
;


-- 
-- TABLE: VETERINARIO 
--

ALTER TABLE VETERINARIO ADD CONSTRAINT RefEMPLEADO20 
    FOREIGN KEY (EMPLEADO_ID)
    REFERENCES EMPLEADO(EMPLEADO_ID)
;


